### ISSUE TITLE
Armstrong Number in java

### ISSUE THREAD

**Issue by sanjanapaidi** [DevSnowflake/hacktoberfest-2021#114]
I want to contribute to this.

**Comment by DevAndromeda** [comment]
sure 👍

**Comment by Kraken-ops** [comment]
I want to contribute to this.

**Comment by abh80** [comment]
Closing this as already merged with commit [cf4f31c](https://github.com/DevSnowflake/hacktoberfest-2021/commit/0a678ec5fcb77912ed22b1a3ca6f8a7ec9bbe107).
