### ISSUE TITLE
weather.py leaks API key

### ISSUE THREAD

**Issue by vierofernando** [DevSnowflake/hacktoberfest-2021#185]
really

https://github.com/DevSnowflake/hacktoberfest-2021/blob/main/Python/weather.py#L3

**Comment by xHyroM** [comment]
Lol

**Comment by KartikeSingh** [comment]
Gg

**Comment by pandyaved98** [comment]
Fixed API Leakage in the issue weather.py leaks API key #185

**Comment by zyrouge** [comment]
Closing this since the PR #206 has been closed with "it was used intentionally".

**Comment by pandyaved98** [comment]
"it was used intentionally". - What does this mean? @zyrouge
